before:
  hooks:
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
builds:
  - main: ./main.go
    id: google-chat
    binary: google-chat
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: mac
      amd64: 64bit-x86

    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"